language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install .
  - bash ./scripts/download_data.sh
# command to run tests
script:
  - cd scripts
  - python run_simulator.py preprocessed 0 params.json PREPROC_OUT
  - python run_simulator.py raw ../ln_data/sample.json params.json JSON_OUT
